Repository nextcloud/monthly_status_email, pull requests merged in 2023-05, with the labels that each got.

#25 fix: update last notification time for opted out notifications
  lib/Service/MailSender.php
  tests/MailSenderTest.php
Labels: bug

#40 Add Cypress test for personal settings
  .eslintrc.js
  .github/workflows/cypress.yml
  cypress.config.js
  cypress/e2e/settings.spec.js
  cypress/runLocal.sh
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/utils/index.js
  package-lock.json
  package.json
Labels: tests

#41 Move cypress to dev dependencies
  package-lock.json
  package.json
Labels: tests

#43 [main] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#46 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies, 3. to review, automated
