Repository nextcloud/monthly_status_email, pull requests merged in 2024-02, with the labels that each got.

#114 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#115 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies, 3. to review, automated

#116 Add support for Nextcloud 28
  CHANGELOG.md
  appinfo/info.xml
Labels: enhancement, 3. to review

#118 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies
